name: AKS Deployment
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: docker build
        run: docker build -t management:'${{github.sha}}' .

      - name: docker login
        run: docker login --username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'

      - name: tag docker image
        run: docker tag purbo75:'${{github.sha}}' '${{secrets.DOCKER_USERNAME}}'/management:'${{github.sha}}'

      - name: push docker image
        run: docker push '${{secrets.DOCKER_USERNAME}}'/management:'${{github.sha}}'

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1
        with:
          creds: "${{secrets.AZURE_CREDENTIALS}}"
          resource-group: TEST
          cluster-name: testcluster

      - name: Create secret in Kubernetes cluster
        uses: Azure/k8s-create-secret@v1.1
        with:
          container-registry-url: https://index.docker.io/v1/
          container-registry-username: "${{secrets.DOCKER_USERNAME}}"
          container-registry-password: "${{secrets.DOCKER_PASSWORD}}"
          secret-type: docker-registry
          secret-name: docker-image-pull-secret

      # Deploy to k8s cluster
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s/backend-deployment.yml
            k8s/backend-service.yml

          images: "${{secrets.DOCKER_USERNAME}}/management:${{github.sha}}"
          imagepullsecrets: docker-image-pull-secret
          action: deploy
